package com.mysampleapp;
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.16
//

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import android.util.Log;
import android.widget.Toast;

import com.amazonaws.mobilehelper.auth.IdentityProvider;
import com.amazonaws.mobilehelper.auth.DefaultSignInResultHandler;
import com.huh.RegistrationActivity;

/**
 * Handles Re-directing to the main activity upon sign-in.
 */
public class SignInHandler extends DefaultSignInResultHandler {
    private static final String LOG_TAG = SignInHandler.class.getSimpleName();

    @Override
    public void onSuccess(final Activity callingActivity, final IdentityProvider provider) {
        if (provider != null) {
            Log.d(LOG_TAG, String.format("User sign-in with %s provider succeeded",
                provider.getDisplayName()));
//            Toast.makeText(callingActivity, String.format(
//                callingActivity.getString(R.string.sign_in_succeeded_message_format),
//                provider.getDisplayName()), Toast.LENGTH_LONG).show();
           // Toast.makeText(callingActivity, "Sign in Successfull",Toast.LENGTH_LONG).show();
            Log.d(LOG_TAG, "Check if Login to Openfire here");
            //TODO: Check if logged into openfire server here

        }

        //TODO: Register to Openfire here

        gotToRegistration(callingActivity);
        //goMain(callingActivity);
    }

    @Override
    public boolean onCancel(final Activity callingActivity) {
        // User abandoned sign in flow.
        final boolean shouldFinishSignInActivity = false;
        return shouldFinishSignInActivity;
    }

    /** Go to the main activity. */
    private void goMain(final Activity callingActivity) {
        callingActivity.startActivity(new Intent(callingActivity, MainActivity.class)
            .setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));
    }

    private void gotToRegistration(final Activity callingActivity) {


        boolean reistered = false;
        try {
            String jidPhoneNumber = PreferenceManager.getDefaultSharedPreferences(callingActivity)
                    .getString("xmpp_jid", null);
            jidPhoneNumber = jidPhoneNumber.replace("+353", "0");
            jidPhoneNumber = jidPhoneNumber.replace(" ", "");
            jidPhoneNumber = jidPhoneNumber.replaceAll("\\s+", "");
            String password = PreferenceManager.getDefaultSharedPreferences(callingActivity)
                    .getString("xmpp_password", null);
            reistered = PreferenceManager.getDefaultSharedPreferences(callingActivity).getBoolean("xmpp_logged_in", false);

            Log.d("SignInHgoToRegistration", "Check if user exists: jidPhoneNumber" + jidPhoneNumber);
            Log.d("SignInHgoToRegistration", "Check if user exists: Registered: " + reistered);
        }
        catch (NullPointerException e){
            e.printStackTrace();
        }
        if(!reistered) {
            callingActivity.startActivity(new Intent(callingActivity, RegistrationActivity.class));
            updateRegistrationStaus(true, callingActivity);
        }
        else{
            goMain(callingActivity);
        }

    }

    private void updateRegistrationStaus(boolean registered, final Activity callingActivity )
    {
        /////
        Log.d("SignUpActivity","saveCredentialsAndLogin() called.");
        //Toast.makeText(getApplicationContext(), TAG + ": saveCredentialsAndLogin() called.", Toast.LENGTH_LONG).show();

        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(callingActivity);
        prefs.edit()
                .putBoolean("xmpp_logged_in",registered)
                .commit();

    }



}
